import type { DB } from "./types";

const now = new Date();
function daysAgo(n: number): string {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return d.toISOString();
}
function daysAhead(n: number): string {
  return daysAgo(-n);
}

export const SEED: DB = {
  users: [
    {
      id: "u-admin",
      name: "Youssef El Amrani",
      email: "admin@stageflow.ma",
      password: "demo1234",
      role: "admin",
      phone: "+212 661 112 233",
      avatarColor: "#4f46e5",
      createdAt: daysAgo(400),
      active: true,
      city: "Casablanca",
    },
    {
      id: "u-s1",
      name: "Salma Bennani",
      email: "salma@stageflow.ma",
      password: "demo1234",
      role: "student",
      phone: "+212 662 445 566",
      avatarColor: "#ec4899",
      createdAt: daysAgo(120),
      active: true,
      filiere: "Développement Digital",
      level: "Spécialisation (T2)",
      city: "Casablanca",
      bio: "Stagiaire passionnée par le full-stack JavaScript. À la recherche d'un stage en développement web.",
      skills: ["React", "Node.js", "TypeScript", "MongoDB", "UI Design"],
    },
    {
      id: "u-s2",
      name: "Mehdi Tazi",
      email: "mehdi@stageflow.ma",
      password: "demo1234",
      role: "student",
      phone: "+212 663 778 899",
      avatarColor: "#0ea5e9",
      createdAt: daysAgo(110),
      active: true,
      filiere: "Infrastructure Digitale",
      level: "Qualification (T1)",
      city: "Rabat",
      skills: ["Linux", "Réseaux", "Docker", "Cisco"],
    },
    {
      id: "u-s3",
      name: "Imane Fassi",
      email: "imane@stageflow.ma",
      password: "demo1234",
      role: "student",
      phone: "+212 664 101 202",
      avatarColor: "#10b981",
      createdAt: daysAgo(95),
      active: true,
      filiere: "Gestion des Entreprises",
      level: "Spécialisation (T2)",
      city: "Marrakech",
      skills: ["Management", "Comptabilité", "Excel", "Analyse"],
    },
    {
      id: "u-s4",
      name: "Anas Cherkaoui",
      email: "anas@stageflow.ma",
      password: "demo1234",
      role: "student",
      avatarColor: "#f59e0b",
      createdAt: daysAgo(60),
      active: true,
      filiere: "Développement Digital",
      level: "Qualification (T1)",
      city: "Tanger",
      skills: ["JavaScript", "Vue.js", "PHP", "MySQL"],
    },
    {
      id: "u-s5",
      name: "Khadija Idrissi",
      email: "khadija@stageflow.ma",
      password: "demo1234",
      role: "student",
      avatarColor: "#8b5cf6",
      createdAt: daysAgo(40),
      active: true,
      filiere: "Marketing Digital",
      level: "Spécialisation (T2)",
      city: "Casablanca",
      skills: ["SEO", "Content", "Google Ads", "Analytics"],
    },
    {
      id: "u-sup1",
      name: "Pr. Nadia Berrada",
      email: "nadia@stageflow.ma",
      password: "demo1234",
      role: "supervisor",
      phone: "+212 665 303 404",
      avatarColor: "#14b8a6",
      createdAt: daysAgo(380),
      active: true,
      filiere: "Développement Digital",
      bio: "Formatrice responsable des stages en développement digital.",
    },
    {
      id: "u-sup2",
      name: "Pr. Karim Lahlou",
      email: "karim@stageflow.ma",
      password: "demo1234",
      role: "supervisor",
      phone: "+212 666 505 606",
      avatarColor: "#f97316",
      createdAt: daysAgo(360),
      active: true,
      filiere: "Infrastructure Digitale",
    },
    {
      id: "u-cmp1",
      name: "RIH - Atos Maroc",
      email: "atos@stageflow.ma",
      password: "demo1234",
      role: "company",
      phone: "+212 522 220 110",
      avatarColor: "#3b82f6",
      createdAt: daysAgo(300),
      active: true,
      companyId: "c1",
    },
    {
      id: "u-cmp2",
      name: "Resp. RH - Inwi",
      email: "inwi@stageflow.ma",
      password: "demo1234",
      role: "company",
      phone: "+212 537 710 220",
      avatarColor: "#6366f1",
      createdAt: daysAgo(290),
      active: true,
      companyId: "c2",
    },
    {
      id: "u-cmp3",
      name: "Resp. Stage - OCP Group",
      email: "ocp@stageflow.ma",
      password: "demo1234",
      role: "company",
      phone: "+212 522 550 330",
      avatarColor: "#0f766e",
      createdAt: daysAgo(280),
      active: true,
      companyId: "c3",
    },
    {
      id: "u-cmp4",
      name: "RH - Capgemini Maroc",
      email: "capgemini@stageflow.ma",
      password: "demo1234",
      role: "company",
      phone: "+212 537 600 440",
      avatarColor: "#0ea5e9",
      createdAt: daysAgo(260),
      active: true,
      companyId: "c4",
    },
  ],

  companies: [
    {
      id: "c1",
      name: "Atos Maroc",
      industry: "Services IT & Cloud",
      city: "Casablanca",
      address: "Twin Center, Bd Zerktouni, Casablanca",
      website: "https://atos.net",
      email: "rh@atos.ma",
      phone: "+212 522 220 110",
      description: "Leader mondial de la transformation digitale, présent à Casablanca depuis 2008.",
      logoColor: "#3b82f6",
      ownerUserId: "u-cmp1",
      partner: true,
      createdAt: daysAgo(300),
    },
    {
      id: "c2",
      name: "Inwi",
      industry: "Télécommunications",
      city: "Rabat",
      address: "Av. Allal El Fassi, Madinat Al Irfane, Rabat",
      website: "https://www.inwi.ma",
      email: "stage@inwi.ma",
      phone: "+212 537 710 220",
      description: "Troisième opérateur télécom au Maroc, filiale du groupe SNI.",
      logoColor: "#6366f1",
      ownerUserId: "u-cmp2",
      partner: true,
      createdAt: daysAgo(290),
    },
    {
      id: "c3",
      name: "OCP Group",
      industry: "Industrie & Mines",
      city: "Casablanca",
      address: "Lot 6, Hay El Makhzen, Casablanca",
      website: "https://www.ocpgroup.ma",
      email: "stage@ocp.ma",
      phone: "+212 522 550 330",
      description: "Leader mondial des roches phosphatées et de la fertilisation.",
      logoColor: "#0f766e",
      ownerUserId: "u-cmp3",
      partner: true,
      createdAt: daysAgo(280),
    },
    {
      id: "c4",
      name: "Capgemini Maroc",
      industry: "Conseil & Technologie",
      city: "Rabat",
      address: "Rue d'Alger, Rabat",
      website: "https://www.capgemini.com",
      email: "rh@capgemini.ma",
      phone: "+212 537 600 440",
      description: "Cabinet mondial de conseil en transformation numérique et ingénierie.",
      logoColor: "#0ea5e9",
      ownerUserId: "u-cmp4",
      partner: true,
      createdAt: daysAgo(260),
    },
    {
      id: "c5",
      name: "Maroc Telecom",
      industry: "Télécommunications",
      city: "Rabat",
      address: "Av. Annakhil, Hay Riad, Rabat",
      website: "https://www.iam.ma",
      email: "stage@iam.ma",
      phone: "+212 537 718 800",
      description: "Premier opérateur global de télécommunications au Maroc.",
      logoColor: "#1d4ed8",
      ownerUserId: "",
      partner: false,
      createdAt: daysAgo(150),
    },
  ],

  offers: [
    {
      id: "o1",
      companyId: "c1",
      title: "Stage - Développeur Web Full-Stack (React/Node)",
      description:
        "Rejoignez l'équipe Plateforme pour développer des applications internes en React et Node.js. Vous participerez au cycle complet : conception, développement, tests et déploiement.",
      filiere: "Développement Digital",
      durationWeeks: 8,
      city: "Casablanca",
      paid: true,
      remote: false,
      skills: ["React", "Node.js", "TypeScript"],
      status: "open",
      createdAt: daysAgo(14),
    },
    {
      id: "o2",
      companyId: "c2",
      title: "Stage - Admin Système & Réseaux Junior",
      description:
        "Au sein de la DSI Inwi, vous assisterez l'équipe infrastructure dans l'administration des serveurs Linux, le monitoring et le déploiement conteneurisé.",
      filiere: "Infrastructure Digitale",
      durationWeeks: 6,
      city: "Rabat",
      paid: true,
      remote: false,
      skills: ["Linux", "Docker", "Réseaux"],
      status: "open",
      createdAt: daysAgo(10),
    },
    {
      id: "o3",
      companyId: "c3",
      title: "Stage - Assistant Gestion de Projet",
      description:
        "Stage au sein du département Projets digitaux d'OCP. Suivi de planning, reporting, coordination entre équipes techniques et métiers.",
      filiere: "Gestion des Entreprises",
      durationWeeks: 10,
      city: "Casablanca",
      paid: true,
      remote: true,
      skills: ["Management", "Excel", "Analyse"],
      status: "open",
      createdAt: daysAgo(7),
    },
    {
      id: "o4",
      companyId: "c4",
      title: "Stage - Développeur Front-End Angular",
      description:
        "Capgemini Maroc recherche un stagiaire pour rejoindre un projet client bancaire. Migration d'une application vers Angular 17.",
      filiere: "Développement Digital",
      durationWeeks: 12,
      city: "Rabat",
      paid: true,
      remote: false,
      skills: ["JavaScript", "Angular", "HTML/CSS"],
      status: "open",
      createdAt: daysAgo(5),
    },
    {
      id: "o5",
      companyId: "c1",
      title: "Stage - Marketing Digital & Growth",
      description:
        "Élaborez et animez la stratégie de contenu, SEO et campagnes d'acquisition pour nos produits SaaS.",
      filiere: "Marketing Digital",
      durationWeeks: 8,
      city: "Casablanca",
      paid: false,
      remote: true,
      skills: ["SEO", "Google Ads", "Content"],
      status: "open",
      createdAt: daysAgo(3),
    },
    {
      id: "o6",
      companyId: "c3",
      title: "Stage - Data Analyst (Power BI)",
      description:
        "Analyse de données opérationnelles et création de tableaux de bord décisionnels sous Power BI.",
      filiere: "Développement Digital",
      durationWeeks: 9,
      city: "Casablanca",
      paid: true,
      remote: false,
      skills: ["SQL", "Power BI", "Analyse"],
      status: "open",
      createdAt: daysAgo(2),
    },
    {
      id: "o7",
      companyId: "c4",
      title: "Stage - DevOps & CI/CD",
      description:
        "Mise en place de pipelines CI/CD, automatisation et culture DevOps sur des projets cloud.",
      filiere: "Infrastructure Digitale",
      durationWeeks: 8,
      city: "Rabat",
      paid: true,
      remote: true,
      skills: ["Docker", "Linux", "Git"],
      status: "closed",
      createdAt: daysAgo(30),
    },
  ],

  applications: [
    {
      id: "a1",
      offerId: "o1",
      studentId: "u-s1",
      companyId: "c1",
      coverLetter:
        "Je suis très intéressée par votre offre. Mon profil full-stack React/Node correspond parfaitement à vos besoins.",
      status: "accepted",
      createdAt: daysAgo(12),
    },
    {
      id: "a2",
      offerId: "o2",
      studentId: "u-s2",
      companyId: "c2",
      coverLetter: "Passionné par l'administration système Linux, je souhaite rejoindre votre équipe DSI.",
      status: "accepted",
      createdAt: daysAgo(9),
    },
    {
      id: "a3",
      offerId: "o1",
      studentId: "u-s4",
      companyId: "c1",
      coverLetter: "Étudiant en développement, je maîtrise JavaScript et Vue.js. Disponible immédiatement.",
      status: "pending",
      createdAt: daysAgo(4),
    },
    {
      id: "a4",
      offerId: "o6",
      studentId: "u-s1",
      companyId: "c3",
      coverLetter: "Curieuse de data, j'aimerais monter en compétences sur Power BI.",
      status: "pending",
      createdAt: daysAgo(2),
    },
    {
      id: "a5",
      offerId: "o3",
      studentId: "u-s3",
      companyId: "c3",
      coverLetter: "En spécialisation gestion, ce stage correspond à mon projet professionnel.",
      status: "rejected",
      createdAt: daysAgo(6),
    },
    {
      id: "a6",
      offerId: "o5",
      studentId: "u-s5",
      companyId: "c1",
      coverLetter: "Spécialisée en marketing digital, je souhaite mettre en pratique mes compétences SEO.",
      status: "pending",
      createdAt: daysAgo(1),
    },
  ],

  internships: [
    {
      id: "i1",
      studentId: "u-s1",
      companyId: "c1",
      offerId: "o1",
      supervisorId: "u-sup1",
      topic: "Plateforme interne de gestion des demandes (React + Node.js)",
      companyMentor: "Hicham Naciri",
      status: "ongoing",
      startDate: daysAgo(28),
      endDate: daysAhead(28),
      hoursPerWeek: 40,
      createdAt: daysAgo(28),
    },
    {
      id: "i2",
      studentId: "u-s2",
      companyId: "c2",
      offerId: "o2",
      supervisorId: "u-sup2",
      topic: "Conteneurisation et monitoring de l'infrastructure DSI",
      companyMentor: "Sara Mounir",
      status: "ongoing",
      startDate: daysAgo(20),
      endDate: daysAhead(22),
      hoursPerWeek: 35,
      createdAt: daysAgo(20),
    },
    {
      id: "i3",
      studentId: "u-s3",
      companyId: "c4",
      supervisorId: "u-sup1",
      topic: "Étude de marché et lancement produit",
      companyMentor: "Omar Belkadi",
      status: "completed",
      startDate: daysAgo(120),
      endDate: daysAgo(30),
      hoursPerWeek: 40,
      createdAt: daysAgo(120),
    },
  ],

  reports: [
    {
      id: "r1",
      internshipId: "i1",
      studentId: "u-s1",
      type: "weekly",
      title: "Semaine 3 — Authentification & maquettes",
      date: daysAgo(7),
      content:
        "Mise en place de l'authentification JWT côté backend (Node/Express). Création des maquettes Figma des écrans principaux. Début des composants React.",
      status: "approved",
      feedback: "Très bon avancement. Pense à documenter l'API avec Swagger.",
      createdAt: daysAgo(7),
    },
    {
      id: "r2",
      internshipId: "i1",
      studentId: "u-s1",
      type: "weekly",
      title: "Semaine 4 — Composants & intégration",
      date: daysAgo(1),
      content:
        "Développement des composants React (Dashboard, Formulaires). Connexion à l'API REST. Gestion des erreurs et états de chargement.",
      status: "submitted",
      createdAt: daysAgo(1),
    },
    {
      id: "r3",
      internshipId: "i2",
      studentId: "u-s2",
      type: "weekly",
      title: "Semaine 2 — Environnement Docker",
      date: daysAgo(2),
      content:
        "Déploiement de l'environnement Docker de test. Configuration du monitoring Prometheus/Grafana.",
      status: "submitted",
      createdAt: daysAgo(2),
    },
    {
      id: "r4",
      internshipId: "i2",
      studentId: "u-s2",
      type: "daily",
      title: "Jour J-2 — Script d'automatisation",
      date: daysAgo(2),
      content: "Rédaction d'un script Bash pour automatiser les sauvegardes.",
      status: "draft",
      createdAt: daysAgo(2),
    },
    {
      id: "r5",
      internshipId: "i3",
      studentId: "u-s3",
      type: "weekly",
      title: "Semaine finale — Restitution",
      date: daysAgo(35),
      content: "Finalisation du rapport et préparation de la présentation.",
      status: "approved",
      feedback: "Excellent travail de synthèse.",
      createdAt: daysAgo(35),
    },
  ],

  evaluations: [
    {
      id: "e1",
      internshipId: "i1",
      type: "midterm",
      score: 16,
      criteria: [
        { label: "Technique", value: 16 },
        { label: "Autonomie", value: 17 },
        { label: "Communication", value: 15 },
        { label: "Assiduité", value: 18 },
      ],
      comment: "Bonne progression technique. Salma montre une réelle autonomie.",
      evaluatorId: "u-sup1",
      createdAt: daysAgo(7),
    },
    {
      id: "e2",
      internshipId: "i3",
      type: "final",
      score: 17,
      criteria: [
        { label: "Technique", value: 16 },
        { label: "Autonomie", value: 18 },
        { label: "Communication", value: 17 },
        { label: "Assiduité", value: 18 },
      ],
      comment: "Stage réussi, livrables de qualité. Félicitations.",
      evaluatorId: "u-sup1",
      createdAt: daysAgo(30),
    },
  ],

  notifications: [
    {
      id: "n1",
      userId: "u-s1",
      title: "Rapport en attente de validation",
      message: "Votre rapport « Semaine 4 » a été soumis à votre encadrant.",
      read: false,
      type: "report",
      createdAt: daysAgo(1),
    },
    {
      id: "n2",
      userId: "u-s1",
      title: "Évaluation intermédiaire disponible",
      message: "Votre encadrant a publié votre évaluation intermédiaire : 16/20.",
      read: false,
      type: "eval",
      createdAt: daysAgo(7),
    },
    {
      id: "n3",
      userId: "u-sup1",
      title: "Nouveau rapport à valider",
      message: "Salma Bennani a soumis son rapport de semaine 4.",
      read: false,
      type: "report",
      createdAt: daysAgo(1),
    },
    {
      id: "n4",
      userId: "u-cmp1",
      title: "Nouvelle candidature",
      message: "Anas Cherkaoui a postulé à votre offre Développeur Web Full-Stack.",
      read: false,
      type: "application",
      createdAt: daysAgo(4),
    },
    {
      id: "n5",
      userId: "u-admin",
      title: "Nouvelle entreprise inscrite",
      message: "Capgemini Maroc a rejoint la plateforme en tant que partenaire.",
      read: true,
      type: "info",
      createdAt: daysAgo(260),
    },
  ],

  conversations: [
    {
      id: "conv1",
      participantIds: ["u-s1", "u-sup1"],
      type: "student-supervisor",
      internshipId: "i1",
      createdAt: daysAgo(28),
    },
    {
      id: "conv2",
      participantIds: ["u-s1", "u-cmp1"],
      type: "student-company",
      internshipId: "i1",
      createdAt: daysAgo(27),
    },
  ],

  messages: [
    {
      id: "m1",
      conversationId: "conv1",
      senderId: "u-sup1",
      text: "Bonjour Salma, comment se passe ta première semaine de stage ?",
      createdAt: daysAgo(27),
    },
    {
      id: "m2",
      conversationId: "conv1",
      senderId: "u-s1",
      text: "Très bien Pr. Berrada ! J'ai mis en place l'authentification et commencé les maquettes.",
      createdAt: daysAgo(26),
    },
    {
      id: "m3",
      conversationId: "conv1",
      senderId: "u-sup1",
      text: "Parfait. Pense à documenter l'API. Bon courage !",
      createdAt: daysAgo(26),
    },
    {
      id: "m4",
      conversationId: "conv2",
      senderId: "u-cmp1",
      text: "Bienvenue chez Atos ! Ton tuteur Hicham t'attendra lundi à 9h.",
      createdAt: daysAgo(27),
    },
    {
      id: "m5",
      conversationId: "conv2",
      senderId: "u-s1",
      text: "Merci beaucoup, hâte de commencer !",
      createdAt: daysAgo(27),
    },
  ],

  soutenances: [
    {
      id: "s1",
      internshipId: "i3",
      studentId: "u-s3",
      date: daysAgo(30),
      time: "10:00",
      room: "Salle de conférence A",
      juryIds: ["u-sup1", "u-admin"],
      presidentId: "u-sup1",
      grade: 17,
      status: "done",
      notes: "Excellente présentation, maîtrise du sujet.",
    },
    {
      id: "s2",
      internshipId: "i1",
      studentId: "u-s1",
      date: daysAhead(26),
      time: "14:00",
      room: "Salle B204",
      juryIds: ["u-sup1", "u-admin"],
      presidentId: "u-admin",
      status: "scheduled",
    },
  ],
};
